description: >
  Sample example description.

usage:
  version: 2.1

  orbs:
    helm: connctd/helm@0.0.1

jobs:
  publish-chart:
    working_directory: ~/tmp
    docker:
      - image: google/cloud-sdk:254.0.0-alpine
    steps:
      - helm/install-helm-client
      - helm/install-helm-gcs-plugin
      - helm/gcp-authorize:
          service-account-credentials: $GCLOUD_SERVICE_ACCOUNT
      - helm/package-and-publish:
          bucket: $HELM_BUCKET_NAME
          chart-version: v0.1.0

workflows:
  use-my-orb:
    jobs:
      - publish-chart:
          context: helm
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]{1,}\.[0-9]{1,}\.[0-9]{1,}$/
